# Generated by Django 4.2.1 on 2023-05-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twillo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsverification',
            name='user',
        ),
        migrations.AddField(
            model_name='smsverification',
            name='phone',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
