# Generated by Django 4.2.1 on 2023-05-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twillo', '0002_remove_smsverification_user_smsverification_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Smsverification',
        ),
    ]
