version: '3.8'

volumes:
  postgres_data: {}
  static_data: {}
  media_data: {}


services:
  web: &web
    container_name: django_web
    depends_on:
      - db
      - redis
    build: .
    volumes:
      - static_data:/path/to/static/in/container:rw
      - .:/app/
      - ./media:/home/app/web/media
      - ./locale:/home/app/web/locale

    env_file: .env
    command: dockerize -wait tcp://db:5432 -timeout 1m gunicorn docker.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8002:8000
    environment:
      - TZ=Asia/Tashkent
    restart: always


  db:
    user: root
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    env_file: .env
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres

    ports:
        - 5433:5432

    restart: always
  redis:
    image: redis

  celery:
    build: .
    command: celery -A myproject worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
