# Generated by Django 4.2.1 on 2023-05-23 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangosignals', '0006_alter_productshop_product_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop_assistant',
            new_name='ShopAssistant',
        ),
        migrations.AlterField(
            model_name='productshop',
            name='product_code',
            field=models.BigIntegerField(blank=True, default=5570329621, null=True, unique=True),
        ),
    ]
