# Generated by Django 4.2.1 on 2023-05-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosignals', '0007_rename_shop_assistant_shopassistant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productshop',
            name='product_code',
            field=models.BigIntegerField(blank=True, default=2468924529, null=True, unique=True),
        ),
    ]
