# Generated by Django 4.2.1 on 2023-07-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangosignals', '0028_alter_productshop_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productshop',
            name='product_code',
            field=models.BigIntegerField(blank=True, default=2209398067, null=True, unique=True),
        ),
    ]
