# Generated by Django 4.2.1 on 2023-07-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakeuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('live_city', models.CharField(max_length=50)),
                ('was_born', models.CharField(max_length=50)),
                ('married', models.BooleanField(default=False)),
                ('language', models.CharField(max_length=50)),
                ('latutude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='fakeimages/')),
            ],
            options={
                'verbose_name': 'Fakeuser',
                'verbose_name_plural': 'Fakeusers',
            },
        ),
    ]
