# Generated by Django 4.2.1 on 2023-07-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fakeuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeuser',
            name='was_born',
            field=models.DateField(),
        ),
    ]
