# Generated by Django 4.2.1 on 2023-07-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fakeuser', '0004_alter_fakeuser_address_alter_fakeuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('symbol', models.CharField(max_length=500)),
                ('rank', models.CharField(max_length=500)),
                ('price_usd', models.CharField(max_length=500)),
                ('price_btc', models.CharField(max_length=500)),
                ('volume_usd_24h', models.CharField(max_length=500)),
                ('market_cap_usd', models.CharField(max_length=500)),
                ('available_supply', models.CharField(max_length=500)),
                ('total_supply', models.CharField(max_length=500)),
                ('max_supply', models.CharField(max_length=500)),
                ('percent_change_1h', models.CharField(max_length=500)),
                ('percent_change_24h', models.CharField(max_length=500)),
                ('percent_change_7d', models.CharField(max_length=500)),
                ('last_updated', models.CharField(max_length=500)),
            ],
        ),
    ]
