# Generated by Django 4.2.1 on 2023-07-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fakeuser', '0005_fakecoin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FakeCoin',
        ),
    ]
