# Generated by Django 4.2.1 on 2023-07-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fakeuser', '0006_delete_fakecoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakeuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=500),
        ),
    ]
