# Generated by Django 4.2.1 on 2023-07-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fakeuser', '0007_fakeuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=500),
        ),
    ]
