# Generated by Django 4.2.1 on 2023-07-12 13:53

import apps.Fakeuser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fakeuser', '0008_alter_fakeuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=apps.Fakeuser.models.default_gender, max_length=500),
        ),
    ]
