# Generated by Django 4.2.1 on 2023-07-14 07:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('image', models.URLField()),
                ('blood_group', models.CharField(max_length=255)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eye_color', models.CharField(max_length=255)),
                ('hair_color', models.CharField(max_length=255)),
                ('hair_type', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('addres', models.JSONField()),
                ('mac_address', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('bank', models.JSONField()),
                ('company', models.JSONField()),
                ('ein', models.CharField(max_length=255)),
                ('ssn', models.CharField(max_length=255)),
                ('user_agent', models.TextField()),
            ],
            options={
                'verbose_name': 'ApiUsers',
                'verbose_name_plural': 'ApiUsers',
                'db_table': 'api_users',
            },
        ),
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'CartProducts',
                'verbose_name_plural': 'CartProducts',
                'db_table': 'cart_products',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('post_id', models.IntegerField()),
                ('user', models.JSONField()),
            ],
            options={
                'verbose_name': 'Comments',
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('images', models.ImageField(upload_to='images')),
                ('extra', models.JSONField()),
            ],
            options={
                'verbose_name': 'ApiImages',
                'verbose_name_plural': 'ApiImages',
                'db_table': 'Apiimages',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('user_id', models.IntegerField()),
                ('tags', models.JSONField()),
                ('reactions', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Posts',
                'verbose_name_plural': 'Posts',
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('stock', models.IntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('thumbnail', models.URLField()),
                ('images', models.JSONField()),
            ],
            options={
                'verbose_name': 'ApiProducts',
                'verbose_name_plural': 'ApiProducts',
                'db_table': 'Apiproducts',
            },
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('tags', models.JSONField()),
                ('likes', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Quotes',
                'verbose_name_plural': 'Quotes',
                'db_table': 'quotes',
            },
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.TextField()),
                ('completed', models.BooleanField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Todos',
                'verbose_name_plural': 'Todos',
                'db_table': 'todos',
            },
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_id', models.IntegerField()),
                ('total_products', models.IntegerField()),
                ('total_quantity', models.IntegerField()),
                ('prducts', models.ManyToManyField(to='JsonLoads.cartproducts')),
            ],
            options={
                'verbose_name': 'Carts',
                'verbose_name_plural': 'Carts',
                'db_table': 'carts',
            },
        ),
    ]
