# Generated by Django 4.2.1 on 2023-07-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JsonLoads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='id',
            new_name='product_id',
        ),
    ]
