# Generated by Django 4.2.1 on 2023-07-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JsonLoads', '0002_rename_id_products_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiusers',
            old_name='addres',
            new_name='address',
        ),
    ]
