# Generated by Django 4.2.1 on 2023-07-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JsonLoads', '0003_rename_addres_apiusers_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='cart_product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
