# Generated by Django 4.2.1 on 2023-07-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JsonLoads', '0004_cartproducts_cart_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproducts',
            name='id',
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='cart_product_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
