# Generated by Django 4.2.1 on 2023-07-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JsonLoads', '0005_remove_cartproducts_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='id',
        ),
        migrations.AddField(
            model_name='carts',
            name='cart_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
